steps:
# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-f'
  - 'Dockerfile.swarm-beta'
  - '-t'
  - 'asia-south1-docker.pkg.dev/likeminds-nonprod-prj-24e1/likeminds-non-prod/swarm-beta:$SHORT_SHA'
  - '.'

# This step pushes the image to Artifact Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'asia-south1-docker.pkg.dev/likeminds-nonprod-prj-24e1/likeminds-non-prod/swarm-beta:$SHORT_SHA'

# generate the manifest
- name: 'gcr.io/cloud-builders/gcloud'
  id: Generate manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed 's/swarm-beta:.*/swarm-beta:${SHORT_SHA}/g' deployment-swarm-beta.yaml

# connect to kubernetes cluster
- name: gcr.io/cloud-builders/gcloud
  id: Connect to kubernetes cluster
  args:
  - beta
  - container
  - clusters
  - get-credentials
  - likeminds-nonprod-autopilot-cluster
  - --project=likeminds-nonprod-prj-24e1
  - --region=asia-south1
  - --internal-ip

- name: gcr.io/cloud-builders/gcloud
  id: Connect to vm
  args:
  - beta
  - compute
  - ssh
  - ayushi_shekhar@likeminds-nonprod-deployment-instance
  - --zone=asia-south1-c
  - --project=likeminds-nonprod-prj-24e1
  - --command="kubectl apply -f /home/ayushi_shekhar/LikeMinds-Swarm/deployment-swarm-beta.yaml -n app-deploy"



# # apply the manifest
# - name: 'gcr.io/cloud-builders/kubectl'
#   id: Deploy
#   args:
#   - 'apply'
#   - '-f'
#   - 'deployment-swarm-beta.yaml'
#   - '-n'
#   - 'app-deploy'
#   env:
#   - 'CLOUDSDK_COMPUTE_REGION=asia-south1'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=likeminds-nonprod-autopilot-cluster'
#   - 'CLOUDSDK_GET_CREDENTIALS_OPTS=--internal-ip'
