steps:
# This step builds the container image.
- name: 'asia.gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-f'
  - 'Dockerfile.swarm-beta'
  - '-t'
  - 'asia.gcr.io/likeminds-nonprod-prj-24e1/github.com/nateshr/likeminds-swarm/swarm-beta:$SHORT_SHA'
  - '.'

# This step pushes the image to Artifact Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'asia.gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'asia.gcr.io/likeminds-nonprod-prj-24e1/github.com/nateshr/likeminds-swarm/swarm-beta:$SHORT_SHA'

# generate the manifest
- name: 'asia.gcr.io/cloud-builders/gcloud'
  id: Generate manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed 's/swarm-beta:.*/swarm-beta:${SHORT_SHA}/g' deployment.yaml

# apply the manifest
- name: 'asia.gcr.io/cloud-builders/kubectl'
  id: Deploy
  args:
  - 'apply'
  - '-f'
  - 'deployment.yaml'
  - '-n'
  - 'app-deploy'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=asia-south1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=likeminds-nonprod-autopilot-cluster'
  