apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "swarm-beta"
  namespace: "app-deploy"
  labels:
    app: "swarm-beta"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "swarm-beta"
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: "swarm-beta"
    spec:
      containers:
      - name: "likeminds-swarm-beta-1"
        image: "asia.gcr.io/likeminds-nonprod-prj-24e1/github.com/nateshr/likeminds-swarm/swarm-beta:45ffd92"
        resources:
          requests:
            memory: "1000Mi"
            cpu: "2000m"
          limits:
            memory: "3000Mi"
            cpu: "2500m"

---

apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "swarm-beta"
  namespace: "app-deploy"
  labels:
    app: "swarm-beta"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "swarm-beta"
    apiVersion: "apps/v1"
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 75
