apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "swarm-beta"
  namespace: "app-deploy"
  labels:
    app: "swarm-beta"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "swarm-beta"
  template:
    metadata:
      labels:
        app: "swarm-beta"
    spec:
      containers:
      - name: "likeminds-swarm-beta-1"
        image: "asia.gcr.io/likeminds-nonprod-prj-24e1/github.com/nateshr/likeminds-swarm/swarm-beta:45ffd92"
