# syntax=docker/dockerfile:1

FROM golang:1.18-alpine
WORKDIR /usr/src/app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . ./

RUN go build -o ./cmd/server/likeminds-swarm cmd/server/likeminds-swarm.go

CMD [ "./cmd/server/likeminds-swarm", "runworker" ]
