# syntax=docker/dockerfile:1

FROM hibiken/asynqmon:latest

# Set the default Redis address (can be overridden by environment variable)
# We are already downloading .env from Azure Blob to while building the image.

# Command to run Asynqmon with the Redis address
CMD ["asynqmon", "--port=8080", "--redis-addr=${ASYNQ_BROKER_ADDRESS}", "--redis-password=${ASYNQ_BROKER_PASSWORD}", "--read-only=true"]
