# syntax=docker/dockerfile:1

FROM hibiken/asynqmon:latest

ENV ASYNQ_BROKER_ADDRESS=likeminds-staging-redis-swarm-worker.privatelink.redis.cache.windows.net:6379

CMD ["asynqmon", "--port=8080", "--redis-addr=${ASYNQ_BROKER_ADDRESS}", "--read-only=true"]

# This Dockerfile is used to build an image for the asynqmon service in a Swarm environment.
# It sets the necessary environment variables for connecting to the Redis broker and starts the asynqmon service in read-only mode.
# The image is built using the latest version of the asynqmon base image.
# The CMD instruction specifies the command to run when the container starts, which includes the port and Redis connection details.
