package constants

const FeedCategory = "Feed"

const (
	CommentPermissionRemovedSubCategory = "Comment permission removed"
	CommentPermissionAddedSubCategory   = "Comment permission added"
	PostPermissionRemovedSubCategory    = "Post permission removed"
	PostPermissionAddedSubCategory      = "Post permission added"
	ModerationPostDeleteSubCategory     = "Moderation delete post"
	ModerationCommentDeleteSubCategory  = "Moderation delete comment"
	ModerationReplyDeleteSubCategory    = "Moderation delete reply"
	PostTagSubCategory                  = "Post Tag"
	CommentTagSubCategory               = "Comment Tag"
	ReplyTagSubCategory                 = "Reply Tag"
	AlsoCommentSubCategory              = "Followed Post"
	PostCommentSubCategory              = "Post Comment"
	CommentReplySubCategory             = "Comment Reply"
	PostLikedSubCategory                = "Post Liked"
	CommentLikedSubCategory             = "Comment Liked"
	RepostOnPostCategory                = "Post Reposted"
)

const (
	PermissionUpdatedTitle = "Permission updated"
	PostDeletedTitle       = "%s deleted"
	CommentDeletedTitle    = "Comment deleted"
	ReplyDeletedTitle      = "Reply deleted"
	LikeTitle              = "New Like!"
	CommentTitle           = "New Comment!"
	ReplyTitle             = "New Reply!"
	TagTitle               = "You are tagged!"
	RepostTitle            = "New Repost!"
)

const (
	CommentPermissionRemovedSubTitle = "Your permission to add comments and replies to the %ss has been removed."
	CommentPermissionAddedSubTitle   = "You now have the permission to add comments on the %ss. Start engaging now."
	PostPermissionRemovedSubTitle    = "Your permission to create %ss in the community has been removed."
	PostPermissionAddedSubTitle      = "You now have the permission to create %ss in the community. Start posting now."
	ModerationPostDeleteSubTitle     = "Your %s has been deleted as it violates community guidelines. Reason: %s"
	ModerationCommentDeleteSubTitle  = "Your comment has been deleted as it violates community guidelines. Reason: %s"
	ModerationReplyDeleteSubTitle    = "Your Reply has been deleted as it violates community guidelines. Reason: %s"
	PostTagSubTitle                  = "%s tagged you in a %s."
	CommentTagSubTitle               = "%s tagged you in a comment."
	ReplyTagSubTitle                 = "%s tagged you in a reply."
	AlsoCommentSubTitleLevelOne      = "%s also commented on %s's %s."
	AlsoCommentSubTitleLevelTwo      = "%s and 1 other also commented on %s's %s."
	AlsoCommentSubTitleLevelThree    = "%s and %d others also commented on %s's %s."
	PostCommentSubTitleLevelOne      = "%s commented on your %s."
	PostCommentSubTitleLevelTwo      = "%s and 1 other commented on your %s."
	PostCommentSubTitleLevelThree    = "%s and %d others commented on your %s."
	CommentReplySubTitleLevelOne     = "%s replied to your comment."
	CommentReplySubTitleLevelTwo     = "%s and 1 other replied to your comment."
	CommentReplySubTitleLevelThree   = "%s and %d others replied to your comment."
	PostLikedSubTitleLevelOne        = "%s liked your %s."
	PostLikedSubTitleLevelTwo        = "%s and 1 other liked your %s."
	PostLikedSubTitleLevelThree      = "%s and %d others liked your %s."
	CommentLikedSubTitleLevelOne     = "%s liked your comment."
	CommentLikedSubTitleLevelTwo     = "%s and 1 other liked your comment."
	CommentLikedSubTitleLevelThree   = "%s and %d others liked your comment."
	PostRepostedSubTitleLevelOne     = "%s reposted your %s."
	PostRepostedSubTitleLevelTwo     = "%s and 1 other reposted your %s."
	PostRepostedSubTitleLevelThree   = "%s and %d others reposted your %s."
)
